package v1

import (
	"time"

	"github.com/opsdata/common-base/pkg/json"
	"gorm.io/gorm"
)

// Extend defines a new type used to store extended fields.
type Extend map[string]interface{}

// String returns the string format of Extend.
func (ext Extend) String() string {
	data, _ := json.Marshal(ext)
	return string(data)
}

// Merge merge extend fields from extendShadow.
func (ext Extend) Merge(extendShadow string) Extend {
	var extend Extend

	// always trust the extendShadow in the database
	_ = json.Unmarshal([]byte(extendShadow), &extend)
	for k, v := range extend {
		if _, ok := ext[k]; !ok {
			ext[k] = v
		}
	}

	return ext
}

// ListMeta describes metadata that synthetic resources must have, including lists and
// various status objects. A resource may have only one of {ObjectMeta, ListMeta}.
type ListMeta struct {
	TotalCount int64 `json:"totalCount,omitempty"`
}

// ObjectMeta is metadata that all persisted resources must have, which includes all objects
// ObjectMeta is also used by gorm.
type ObjectMeta struct {
	// ID
	// - 映射数据库中id字段
	// - be typically generated by the storage on successful creation of a resource and is not
	// allowed to change on PUT operations
	// - be populated by the system and read-only
	ID uint64 `json:"id,omitempty" gorm:"primary_key;AUTO_INCREMENT;column:id"`

	// InstanceID
	// - 资源唯一标识
	// - 其生成和更新都是自动化的: 通过gorm提供的AfterCreate Hooks在记录插入数据库之后生成并更新到数据库中
	// - define a string type resource identifier,
	// - use prefixed to distinguish resource types, easy to remember, and url-friendly
	InstanceID string `json:"instance_id,omitempty" gorm:"unique;column:instance_id;type:varchar(32);not null"`

	// Name
	// - 资源名称: 可以通过名字很容易地辨别一个资源
	// - required: true
	// - must be unique
	// - required when creating resources and can not be updated
	// - be primarily intended for creation idempotence and configuration definition
	// Name string `json:"name,omitempty" gorm:"column:name;type:varchar(64);not null" validate:"name"`

	// Extend
	// - 类型别名: map[string]interface{}
	// - 在保存到数据库中时，会自动Marshal成字符串保存在ExtendShadow字段中
	// 1.func (obj *ObjectMeta) BeforeCreate(tx *gorm.DB) error
	// 2.func (obj *ObjectMeta) BeforeUpdate(tx *gorm.DB) error
	// - store the fields that need to be added but do not want to add a new column
	Extend Extend `json:"extend,omitempty" gorm:"-"`

	// ExtendShadow
	// - 当从数据库查询数据时，ExtendShadow的值会自动Unmarshal到Extend类型的变量中供程序使用
	// 1.func (obj *ObjectMeta) AfterFind(tx *gorm.DB) error
	// - the shadow of Extend and DO NOT modify directly
	ExtendShadow string `json:"-" gorm:"column:extend_shadow"`

	// CreatedAt is a timestamp representing the server time when this object was
	// created. It is not guaranteed to be set in happens-before order across separate operations.
	// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
	//
	// Populated by the system.
	// Read-only.
	// Null for lists.
	CreatedAt time.Time `json:"created_at,omitempty" gorm:"column:created_at"`

	// UpdatedAt is a timestamp representing the server time when this object was updated.
	// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
	//
	// Populated by the system.
	// Read-only.
	// Null for lists.
	UpdatedAt time.Time `json:"updated_at,omitempty" gorm:"column:updated_at"`

	// DeletedAt is RFC 3339 date and time at which this resource will be deleted. This
	// field is set by the server when a graceful deletion is requested by the user, and is not
	// directly settable by a client.
	//
	// Populated by the system when a graceful deletion is requested.
	// Read-only.
	// DeletedAt gorm.DeletedAt `json:"-" gorm:"column:deletedAt;index:idx_deletedAt"`
}

// BeforeCreate run before create database record.
func (obj *ObjectMeta) BeforeCreate(tx *gorm.DB) error {
	obj.ExtendShadow = obj.Extend.String()

	return nil
}

// BeforeUpdate run before update database record.
func (obj *ObjectMeta) BeforeUpdate(tx *gorm.DB) error {
	obj.ExtendShadow = obj.Extend.String()

	return nil
}

// AfterFind run after find to unmarshal a extend shadown string into metav1.Extend struct.
func (obj *ObjectMeta) AfterFind(tx *gorm.DB) error {
	if err := json.Unmarshal([]byte(obj.ExtendShadow), &obj.Extend); err != nil {
		return err
	}

	return nil
}

// TypeMeta describes an individual object in an API response or request
// with strings representing the type of the object and its API schema version.
// Structures that are versioned or persisted should inline TypeMeta.
type TypeMeta struct {
	// Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// required: false
	Kind string `json:"kind,omitempty"`

	// APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	APIVersion string `json:"apiVersion,omitempty"`
}

// ListOptions is the query options to a standard REST list call.
type ListOptions struct {
	TypeMeta `json:",inline"`

	// LabelSelector is used to find matching REST resources.
	LabelSelector string `json:"labelSelector,omitempty" form:"labelSelector"`

	// FieldSelector restricts the list of returned objects by their fields. Defaults to everything.
	FieldSelector string `json:"fieldSelector,omitempty" form:"fieldSelector"`

	// TimeoutSeconds specifies the seconds of ClientIP type session sticky time.
	TimeoutSeconds *int64 `json:"timeoutSeconds,omitempty"`

	// Offset specify the number of records to skip before starting to return the records.
	Offset *int64 `json:"offset,omitempty" form:"offset"`

	// Limit specify the number of records to be retrieved.
	Limit *int64 `json:"limit,omitempty" form:"limit"`
}

// ExportOptions is the query options to the standard REST get call.
// Deprecated. Planned for removal in 1.18.
type ExportOptions struct {
	TypeMeta `json:",inline"`

	// Should this value be exported.  Export strips fields that a user can not specify.
	// Deprecated. Planned for removal in 1.18.
	Export bool `json:"export"`

	// Should the export be exact.  Exact export maintains cluster-specific fields like 'Namespace'.
	// Deprecated. Planned for removal in 1.18.
	Exact bool `json:"exact"`
}

// GetOptions is the standard query options to the standard REST get call.
type GetOptions struct {
	TypeMeta `json:",inline"`
}

// DeleteOptions may be provided when deleting an API object.
type DeleteOptions struct {
	TypeMeta `json:",inline"`

	// +optional
	Unscoped bool `json:"unscoped"`
}

// CreateOptions may be provided when creating an API object.
type CreateOptions struct {
	TypeMeta `json:",inline"`

	// When present, indicates that modifications should not be
	// persisted. An invalid or unrecognized dryRun directive will
	// result in an error response and no further processing of the
	// request. Valid values are:
	// - All: all dry run stages will be processed
	// +optional
	DryRun []string `json:"dryRun,omitempty"`
}

// PatchOptions may be provided when patching an API object.
// PatchOptions is meant to be a superset of UpdateOptions.
type PatchOptions struct {
	TypeMeta `json:",inline"`

	// When present, indicates that modifications should not be
	// persisted. An invalid or unrecognized dryRun directive will
	// result in an error response and no further processing of the
	// request. Valid values are:
	// - All: all dry run stages will be processed
	// +optional
	DryRun []string `json:"dryRun,omitempty"`

	// Force is going to "force" Apply requests. It means user will
	// re-acquire conflicting fields owned by other people. Force
	// flag must be unset for non-apply patch requests.
	// +optional
	Force bool `json:"force,omitempty"`
}

// UpdateOptions may be provided when updating an API object.
// All fields in UpdateOptions should also be present in PatchOptions.
type UpdateOptions struct {
	TypeMeta `json:",inline"`

	// When present, indicates that modifications should not be
	// persisted. An invalid or unrecognized dryRun directive will
	// result in an error response and no further processing of the
	// request. Valid values are:
	// - All: all dry run stages will be processed
	// +optional
	DryRun []string `json:"dryRun,omitempty"`
}

// AuthorizeOptions may be provided when authorize an API object.
type AuthorizeOptions struct {
	TypeMeta `json:",inline"`
}

// TableOptions are used when a Table is requested by the caller.
type TableOptions struct {
	TypeMeta `json:",inline"`

	// NoHeaders is only exposed for internal callers. It is not included in our OpenAPI definitions
	// and may be removed as a field in a future release.
	NoHeaders bool `json:"-"`
}

/*
 * ELMT options
 */

// SqlOptions may be provided when directly executing the SQL statement.
type SqlOptions struct {
	Statement string `json:"sql"`
	Condition string `json:"condition"`
	Order     string `json:"order"`
	Offset    *int64 `json:"offset,omitempty"`
	Limit     *int64 `json:"limit,omitempty"`
}

// AlertQueryOptions may be provided when querying the alerts data.
type AlertQueryOptions struct {
	StartTime   string `json:"start_time"`   // 开始时间
	EndTime     string `json:"end_time"`     // 结束时间
	EventStatus string `json:"event_status"` // 告警状态: 1,2,3
	Severity    string `json:"severity"`     // 严重级别: 0,3,5
}

// AlertActionOptions may be provided when taking action on the specified alert or alerts.
type AlertActionOptions struct {
	Serial   int    `json:"serial"`
	UserID   int    `json:"user_id"`
	UserName string `json:"user_name"`
}

// AlertJournalOptions may be provided when querying the alert journals.
type AlertJournalOptions struct {
	Serial int `json:"serial"`
}

// MetricOptions may be provided when retrieving the instant data of metrics.
type MetricOptions struct {
	AppAlias   string `json:"app_alias"`   // 业务名称
	HostName   string `json:"host_name"`   // 主机名称
	ItemKey    string `json:"item_key"`    // 指标名称
	ObjectType string `json:"object_type"` // 对象类型
	Source     string `json:"source"`      // 监控工具
}

// MetricHistoryOptions may be provided when retrieving the history data of metrics.
type MetricHistoryOptions struct {
	HostId    int    `json:"host_id"`    // 主机内部标识
	ItemKey   string `json:"item_key"`   // 监控指标名称
	ItemType  int    `json:"item_type"`  // 监控指标类型: 0-numeric float, 1-character, 2-log, 3-numeric signed, 4-text
	IsMulti   bool   `json:"is_multi"`   // 是否有多实例: 如文件系统、网络接口等
	StartTime string `json:"start_time"` // 查询开始时间
	EndTime   string `json:"end_time"`   // 查询截止时间
}
